### ISSUE TITLE
Instance Mercredis

### ISSUE THREAD

**Issue by ghost** [Groupe-AMY/projetweb_ecommerce-horlogerie#2]
#### Monsieur @NicolasGlassey,

Pourrait-on avoir l'instance de WordPress chaque mercredi de 15h à 23h ?

Merci d'avance.

**Comment by NicolasGlassey** [comment]
Monsieur,
Le nécessaire a été fait pour automatiser le lancement et l'arrêt de votre insatnce durant les périodes demandées.

Tous les mercredis, de 15h00 à 23h00. (en plus des heures de cours)

Une image complète sera également effectuée 5 min après son arrêt.

Cordialement
