### ISSUE TITLE
FQDN

### ISSUE THREAD

**Issue by NicolasGlassey** [Groupe-AMY/projetweb_ecommerce-horlogerie#3]
Monsieur Baudraz,

Il y avait une erreur de référencement dans le DNS (de mon côté).

Voici les preuves que tout fonctionne bien suite à ma correction. Je ne connais pas le temps de mise à jour du DNS du CPNV. Mais depuis hors du réseau du CPNV... tout est bon.

![image](https://user-images.githubusercontent.com/5616312/46763767-f6c76680-ccda-11e8-802b-8d4c23c8b51f.png)

![image](https://user-images.githubusercontent.com/5616312/46763884-39893e80-ccdb-11e8-839a-fe6be9a1ffc4.png)

Redites-moi si vous obtenez le même résultat.

Bonne soirée

**Comment by ghost** [comment]
Le résultat était le même chez moi, merci.
