### ISSUE TITLE
Instance pour les vacances 

### ISSUE THREAD

**Issue by ghost** [Groupe-AMY/projetweb_ecommerce-horlogerie#4]
Bonjour Monsieur,

Vous aviez demandé qu'on vous commande l'instance avant midi, excusez nous du retard.

Pourrait-on avoir l'instance tous les jours de ces vacances de 10h à minuit ?

Bonne journée

**Comment by NicolasGlassey** [comment]
C'est tout bon. J'ai inclu cela au "dashboard" des réservations.

Profitez aussi de souffler un peu Yannick... vous avez aussi le droit de relâcher un peu la pression, ok ?
