### ISSUE TITLE
Démonstration du 16.11.2018

### ISSUE THREAD

**Issue by ghost** [Groupe-AMY/projetweb_ecommerce-horlogerie#7]
Bonsoir M. @NicolasGlassey ,

Pour la présentation de vendredi prochain, nous aimerions être sûr d'avoir bien compris.

Il y aura une partie démo, comme nous l'avions fait devant vous et M.Boillat.
Ainsi qu'un "Sprint Review (ou sprint retrospective ?)" comme vous nous l'aviez expliqué en cours (montrer les points d'amélioration que vous nous aviez donné).

Concernant le powerpoint cependant, nous n'arrivons pas à comprendre comment faire pour en avoir un en plus d'une démo de l'application ?

J'espère que c'est assez compréhensible.

Cordialement

Yannick Baudraz

**Comment by NicolasGlassey** [comment]
Bonjour,

Je vous ai répondu par email (à tous les scrums masters).

Cordialement
